name: pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run application to verify it starts
        run: |
          poetry run uvicorn main:app --host 127.0.0.1 --port 8000 &
          sleep 5
          curl --fail http://127.0.0.1:8000 || exit 1

      - name: Run tests
        run: |
          poetry run pytest

  build-and-push-image:
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/mart337i/fastapi-template:latest
            ghcr.io/mart337i/fastapi-template:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" > ./envfile

      - name: Verify deployment files
        run: |
          test -f docker-stack.yaml || (echo "docker-stack.yaml missing!" && exit 1)

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: fastapi-template
          file: docker-stack.yaml
          host: egeskov-group.dk
          user: deployment
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./envfile
